project_id = "parenting-trial-database"

[functions.submit-trial-response]
verify_jwt = false
[functions.get-editable-response]
verify_jwt = false
[functions.update-trial-response]
verify_jwt = false
[functions.delete-trial-response]
verify_jwt = false
